name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Emacs
        uses: purcell/setup-emacs@master
        with:
          version: '30.1'
      - name: Run tests
        run: |
          files=$(find test -name "*.el" -print)
          emacs -Q --batch -L . $files -l ert -f ert-run-tests-batch-and-exit
